# mcrecover: PCRE options for GCN MemCard Recover.

SET(PCRE_BUILD_PCRE8 OFF) # TODO: Disable once pcre16 is working.
SET(PCRE_BUILD_PCRE16 ON)
SET(PCRE_BUILD_PCRE32 OFF)
SET(PCRE_BUILD_PCRECPP OFF)

SET(PCRE_EBCDIC OFF)
SET(PCRE_EBCDIC_NL25 OFF)
SET(PCRE_LINK_SIZE "2")
SET(PCRE_PARENS_NEST_LIMIT "250")
SET(PCRE_MATCH_LIMIT "10000000")
SET(PCRE_MATCH_LIMIT_RECURSION "MATCH_LIMIT")
SET(PCREGREP_BUFSIZE "20480")
SET(PCRE_NEWLINE "LF")
SET(PCRE_NO_RECURSE OFF)
SET(PCRE_POSIX_MALLOC_THRESHOLD "10")
SET(PCRE_SUPPORT_JIT OFF)		# TODO
SET(PCRE_SUPPORT_PCREGREP_JIT ON)
SET(PCRE_SUPPORT_UTF ON)		# REQUIRED
SET(PCRE_SUPPORT_UNICODE_PROPERTIES ON)	# REQUIRED for some Japanese games
SET(PCRE_SUPPORT_BSR_ANYCRLF OFF)
SET(PCRE_SUPPORT_VALGRIND OFF)

SET(PCRE_SHOW_REPORT OFF)
SET(PCRE_BUILD_PCREGREP OFF)
SET(PCRE_BUILD_TESTS OFF)

SET(PCRE_REBUILD_CHARTABLES OFF)
