# Microsoft Visual C++

# CMake has a bunch of defaults, including /Od for debug and /O2 for release.
# Remove some default CFLAGS/CXXFLAGS.
STRING(REPLACE "/GR" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
STRING(REPLACE "/EHsc" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

# Disable useless warnings:
# - MSVC "logo" messages
# - C4355: 'this' used in base member initializer list (used for Qt Dpointer pattern)
# - MSVCRT "deprecated" functions
SET(MCRECOVER_BASE_C_FLAGS_COMMON "-nologo -wd4355 -D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE")
SET(MCRECOVER_BASE_CXX_FLAGS_COMMON "${MCRECOVER_BASE_C_FLAGS_COMMON}")
# NOTE: -tsaware is automatically set for Windows 2000 and later. (as of at least Visual Studio .NET 2003)
SET(MCRECOVER_BASE_EXE_LINKER_FLAGS_COMMON "-nologo /manifest:no -dynamicbase -nxcompat -largeaddressaware")
SET(MCRECOVER_BASE_SHARED_LINKER_FLAGS_COMMON "${MCRECOVER_BASE_EXE_LINKER_FLAGS_COMMON}")

# Disable C++ RTTI and asynchronous exceptions.
SET(MCRECOVER_BASE_CXX_FLAGS_COMMON "${MCRECOVER_BASE_CXX_FLAGS_COMMON} -GR- -EHsc")

# Disable the RC and MASM "logo".
SET(CMAKE_RC_FLAGS "-nologo")
SET(CMAKE_ASM_MASM_FLAGS "-nologo")

# Check for link-time optimization.
IF(ENABLE_LTO)
	SET(MCRECOVER_BASE_C_FLAGS_COMMON "${MCRECOVER_BASE_C_FLAGS_COMMON} -GL")
	SET(MCRECOVER_BASE_CXX_FLAGS_COMMON "${MCRECOVER_BASE_CXX_FLAGS_COMMON} -GL")
	SET(MCRECOVER_BASE_EXE_LINKER_FLAGS_COMMON "${MCRECOVER_BASE_EXE_LINKER_FLAGS_COMMON} -LTCG")
ENDIF(ENABLE_LTO)

# Check if CMAKE_SIZEOF_VOID_P is set correctly.
IF(NOT CMAKE_SIZEOF_VOID_P)
	# CMAKE_SIZEOF_VOID_P isn't set.
	# Set it based on CMAKE_CL_64.
	IF(CMAKE_CL_64)
		SET(CMAKE_SIZEOF_VOID_P 8)
	ELSE(CMAKE_CL_64)
		SET(CMAKE_SIZEOF_VOID_P 4)
	ENDIF(CMAKE_CL_64)
ENDIF(NOT CMAKE_SIZEOF_VOID_P)

# Debug/release flags.
SET(MCRECOVER_BASE_C_FLAGS_DEBUG		"-Zi")
SET(MCRECOVER_BASE_CXX_FLAGS_DEBUG		"-Zi")
SET(MCRECOVER_BASE_EXE_LINKER_FLAGS_DEBUG	"-debug -incremental:no")
SET(MCRECOVER_BASE_SHARED_LINKER_FLAGS_DEBUG	"${MCRECOVER_BASE_EXE_LINKER_FLAGS_DEBUG}")
SET(MCRECOVER_BASE_C_FLAGS_RELEASE		"-Zi")
SET(MCRECOVER_BASE_CXX_FLAGS_RELEASE		"-Zi")
SET(MCRECOVER_BASE_EXE_LINKER_FLAGS_RELEASE	"-debug -incremental:no")
SET(MCRECOVER_BASE_SHARED_LINKER_FLAGS_RELEASE	"${MCRECOVER_BASE_EXE_LINKER_FLAGS_DEBUG}")
