# Microsoft Visual C++

# Remove some default CFLAGS/CXXFLAGS.
STRING(REPLACE "/GR" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
STRING(REPLACE "/EHsc" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

# Disable useless warnings:
# - MSVC "logo" messages
# - C4355: 'this' used in base member initializer list (used for Qt Dpointer pattern)
# - MSVCRT "deprecated" functions
SET(MCRECOVER_BASE_C_FLAGS_COMMON "-nologo -wd4355 -D_CRT_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE")
SET(MCRECOVER_BASE_CXX_FLAGS_COMMON "${MCRECOVER_BASE_C_FLAGS_COMMON}")
# NOTE: -tsaware is automatically set for Windows 2000 and later. (as of at least Visual Studio .NET 2003)
# FIXME: If built as 64-bit, needs -subsystem:windows,5.02.
SET(MCRECOVER_BASE_EXE_LINKER_FLAGS_COMMON "-nologo /manifest:no -subsystem:windows,5.01 -dynamicbase -nxcompat -largeaddressaware")
SET(MCRECOVER_BASE_SHARED_LINKER_FLAGS_COMMON "${MCRECOVER_BASE_EXE_LINKER_FLAGS_COMMON}")

# Disable C++ RTTI and asynchronous exceptions.
SET(MCRECOVER_BASE_CXX_FLAGS_COMMON "${MCRECOVER_BASE_CXX_FLAGS_COMMON} -GR- -EHsc")

# Disable the RC and MASM "logo".
SET(CMAKE_RC_FLAGS "-nologo")
SET(CMAKE_ASM_MASM_FLAGS "-nologo")

# Check for link-time optimization.
IF(ENABLE_LTO)
	SET(MCRECOVER_BASE_C_FLAGS_COMMON "${MCRECOVER_BASE_C_FLAGS_COMMON} -GL")
	SET(MCRECOVER_BASE_CXX_FLAGS_COMMON "${MCRECOVER_BASE_CXX_FLAGS_COMMON} -GL")
	SET(MCRECOVER_BASE_EXE_LINKER_FLAGS_COMMON "${MCRECOVER_BASE_EXE_LINKER_FLAGS_COMMON} -LTCG")
ENDIF(ENABLE_LTO)

# Debug/release flags.
SET(MCRECOVER_BASE_C_FLAGS_DEBUG "-Zi")
SET(MCRECOVER_BASE_CXX_FLAGS_DEBUG "-Zi")
SET(MCRECOVER_BASE_EXE_LINKER_FLAGS_DEBUG "-debug -incremental:no")
SET(MCRECOVER_BASE_SHARED_LINKER_FLAGS_DEBUG "${MCRECOVER_BASE_EXE_LINKER_FLAGS_DEBUG}")
SET(MCRECOVER_BASE_C_FLAGS_RELEASE "-Zi")
SET(MCRECOVER_BASE_CXX_FLAGS_RELEASE "-Zi")
SET(MCRECOVER_BASE_EXE_LINKER_FLAGS_RELEASE "-debug -incremental:no")
SET(MCRECOVER_BASE_SHARED_LINKER_FLAGS_RELEASE "${MCRECOVER_BASE_EXE_LINKER_FLAGS_DEBUG}")
